Home work 3
fumika777/home-work pull request #3
Opened 2021-12-07 15:47 UTC by fumika777

Готовое дз 3

2021-12-16 07:18 UTC, Upforup requested changes

2021-12-16 07:18 UTC, Upforup commented on src/main/java/com/sbrf/reboot/AccountRepository.java
> +    Set<Account> repository = null;
Зачем нужно это поле? Поля в интерфейсах являются константами ( public static final)

2021-12-16 07:18 UTC, Upforup commented on src/main/java/com/sbrf/reboot/AccountService.java
> +    private AccountRepository repository;
Final

2021-12-16 07:18 UTC, Upforup commented on src/test/java/com/sbrf/reboot/service/AccountServiceTest.java
> +    AccountRepository accountRepository;
В setUp, мок инициализируются через статический метод, можно не использовать аннотацию.

2021-12-16 07:18 UTC, Upforup commented on src/main/java/com/sbrf/reboot/Account.java
> +public class Account {
В данном классе определены поля с доступом private и в то же время не определены методы которые бы предоставляли доступ к этим полям пользователям. Также, чтобы проверка на вхождение в множество работала корректно, нужно переопределить equals/hashcode. Все это можно реализовать самостоятельно и в занятиях по коллекциям эта тема освещается, но для данного решения достаточно добавить \@Data или \@Value и Lombok автоматически сгенерирует нужные методы

2021-12-16 13:10 UTC, RodinDenis approved these changes

2022-01-10 17:48 UTC, fumika777 commented on src/main/java/com/sbrf/reboot/AccountService.java
> +    private AccountRepository repository;
почему здесь нужен final? я через конструктор в тестах назначаю репозиторий? т.е. мне нужно будет менять эту переменную

2022-02-12 17:01 UTC, merged